# 집합

In [2]:
setS= {1,2,3,4,5,6}

In [3]:
setS

{1, 2, 3, 4, 5, 6}

In [4]:
setS.remove(4)

In [5]:
setS

{1, 2, 3, 5, 6}

In [6]:
setS.clear()

In [7]:
setS

set()

# 딕셔너리

In [9]:
test = {"kim":90, "jeong":89, "park":60}

In [16]:
test["kim"]

90

In [20]:
test.keys()

dict_keys(['kim', 'jeong', 'park'])

In [21]:
test.values()

dict_values([90, 89, 60])

In [27]:
test.items()

dict_items([('jeong', 89), ('park', 60), ('kim', 90)])

In [24]:
del test["kim"]

In [25]:
test

{'jeong': 89, 'park': 60}

In [26]:
test["kim"]=90

In [28]:
 'kim' in test

True

# Numpy

In [2]:
import numpy as np

In [3]:
v1 = np.array([1,2,3,4,5])

In [34]:
int[] odds = {1, 3, 5, 7, 9};

SyntaxError: invalid syntax (<ipython-input-34-faf67b233912>, line 1)

In [41]:
v1 = np.arange(10)
v2 = np.arange(1.5,10,2, dtype=float)
v3 = np.arange(1.5,10,2, dtype=float)**2
print(v1)
print(v2)
print(v3)

[0 1 2 3 4 5 6 7 8 9]
[1.5 3.5 5.5 7.5 9.5]
[ 2.25 12.25 30.25 56.25 90.25]


In [46]:
v4= v1.reshape(2,5) #행렬 만들기
print(v4)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [47]:
np.add(v2,v3)

array([ 3.75, 15.75, 35.75, 63.75, 99.75])

In [49]:
np.subtract(v2,v3)

array([ -0.75,  -8.75, -24.75, -48.75, -80.75])

In [50]:
np.multiply(v2,v3)

array([  3.375,  42.875, 166.375, 421.875, 857.375])

In [51]:
np.dot(v2,v3) # 행렬 연산

1491.875

In [53]:
# np.add(v1,v2) 크기가 달라서 에러

In [71]:
v5 = np.arange(16).reshape(4,2,2,order='f') #C', 'F', 'A', or 'K'

In [72]:
v5

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [73]:
print(np.max(v5))

15


In [74]:
v5.max()

15

In [79]:
v2.dtype

dtype('float64')

In [6]:
np.where(v1== 1) # 해당하는 index 반환

(array([0], dtype=int64),)

# Pandas

In [83]:
import pandas as pd
from pandas import Series,DataFrame

In [88]:
a=Series([1,3,5,7]) # index와 value의 형태를 갖고 있는 pandas의 자료 구조입니다.

In [89]:
a.values

array([1, 3, 5, 7], dtype=int64)

In [90]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [92]:
a=Series([1,3,5,7], index = ['a','b','c','d'])

In [95]:
a.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [96]:
df = pd.read_csv("C:\\Users\\user\\빅분기 실기\\[1]BigData_data_최종본(0910)\\EX_GrapeData.csv")

In [97]:
df

continent  brand  size  period price
0           2      2  10.7   47.65   144
1           2      3  14.0   63.13   215
2           2      2   9.0   58.76   105
3           1      1   8.0   34.88    69
4           2      2  10.0   55.53   134
..        ...    ...   ...     ...   ...
58          1      1   5.0   16.66  21.5
59          2      1  21.0   43.00      
60          2      2   5.0   12.00      
61          2      3  13.0   20.00      
62          2      3  31.0   19.00      

[63 rows x 5 columns]

In [179]:
df = pd.read_excel("C:\\Users\\user\\빅분기 실기\\[1]BigData_data_최종본(0910)\\EX_GrapeData.xlsx")

In [101]:
df.head()

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0

In [102]:
df.tail()

continent  brand  size  period  price
58          1      1   5.0   16.66   21.5
59          2      1  21.0   43.00    NaN
60          2      2   5.0   12.00    NaN
61          2      3  13.0   20.00    NaN
62          2      3  31.0   19.00    NaN

In [103]:
df[1:6]

continent  brand  size  period  price
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0
5          2      2  10.5   43.14  129.0

In [105]:
df[:10]

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0
5          2      2  10.5   43.14  129.0
6          2      2  16.0   54.86  155.0
7          2      1  15.0   44.14   99.0
8          2      1   6.5   17.46   38.5
9          2      1   5.0   21.04   36.5

In [106]:
df[60:]

continent  brand  size  period  price
60          2      2   5.0    12.0    NaN
61          2      3  13.0    20.0    NaN
62          2      3  31.0    19.0    NaN

In [107]:
df['price']

0     144.0
1     215.0
2     105.0
3      69.0
4     134.0
      ...  
58     21.5
59      NaN
60      NaN
61      NaN
62      NaN
Name: price, Length: 63, dtype: float64

In [108]:
df[['price']]

price
0   144.0
1   215.0
2   105.0
3    69.0
4   134.0
..    ...
58   21.5
59    NaN
60    NaN
61    NaN
62    NaN

[63 rows x 1 columns]

In [114]:
df.columns[[0,1,2]]

Index(['continent', 'brand', 'size'], dtype='object')

In [115]:
df.columns[0:3]

Index(['continent', 'brand', 'size'], dtype='object')

In [116]:
df[df.columns[[0,1,2]]]

continent  brand  size
0           2      2  10.7
1           2      3  14.0
2           2      2   9.0
3           1      1   8.0
4           2      2  10.0
..        ...    ...   ...
58          1      1   5.0
59          2      1  21.0
60          2      2   5.0
61          2      3  13.0
62          2      3  31.0

[63 rows x 3 columns]

In [124]:
df.loc[1:10,'size':'price']

size  period  price
1   14.0   63.13  215.0
2    9.0   58.76  105.0
3    8.0   34.88   69.0
4   10.0   55.53  134.0
5   10.5   43.14  129.0
6   16.0   54.86  155.0
7   15.0   44.14   99.0
8    6.5   17.46   38.5
9    5.0   21.04   36.5
10  25.0  109.38  260.0

In [131]:
df.loc[:,'size':]

size  period  price
0   10.7   47.65  144.0
1   14.0   63.13  215.0
2    9.0   58.76  105.0
3    8.0   34.88   69.0
4   10.0   55.53  134.0
..   ...     ...    ...
58   5.0   16.66   21.5
59  21.0   43.00    NaN
60   5.0   12.00    NaN
61  13.0   20.00    NaN
62  31.0   19.00    NaN

[63 rows x 3 columns]

In [132]:
df.iloc[1:10,2:] # iloc숫자로 가능

size  period  price
1  14.0   63.13  215.0
2   9.0   58.76  105.0
3   8.0   34.88   69.0
4  10.0   55.53  134.0
5  10.5   43.14  129.0
6  16.0   54.86  155.0
7  15.0   44.14   99.0
8   6.5   17.46   38.5
9   5.0   21.04   36.5

In [134]:
df.iloc[1:10,0:3]

continent  brand  size
1          2      3  14.0
2          2      2   9.0
3          1      1   8.0
4          2      2  10.0
5          2      2  10.5
6          2      2  16.0
7          2      1  15.0
8          2      1   6.5
9          2      1   5.0

In [135]:
df.loc[1:10,'continent':'size']

continent  brand  size
1           2      3  14.0
2           2      2   9.0
3           1      1   8.0
4           2      2  10.0
5           2      2  10.5
6           2      2  16.0
7           2      1  15.0
8           2      1   6.5
9           2      1   5.0
10          2      2  25.0

In [137]:
df.at[5,'size']

10.5

In [138]:
df_copy = df.copy()

In [140]:
df_copy.head()

continent  brand  size  period  price
0          2      2  10.7   47.65  144.0
1          2      3  14.0   63.13  215.0
2          2      2   9.0   58.76  105.0
3          1      1   8.0   34.88   69.0
4          2      2  10.0   55.53  134.0

In [141]:
df_copy = df_copy[['size','period','price']]

In [142]:
df_copy.head()

size  period  price
0  10.7   47.65  144.0
1  14.0   63.13  215.0
2   9.0   58.76  105.0
3   8.0   34.88   69.0
4  10.0   55.53  134.0

In [144]:
df_copy.rename(columns = {'period':'time'},inplace=True)

In [147]:
df_copy.columns

Index(['size', 'time', 'price'], dtype='object')

In [148]:
df_copy['growth'] = df['size']/ df['period']

In [149]:
df_copy.head()

size   time  price    growth
0  10.7  47.65  144.0  0.224554
1  14.0  63.13  215.0  0.221765
2   9.0  58.76  105.0  0.153165
3   8.0  34.88   69.0  0.229358
4  10.0  55.53  134.0  0.180083

In [150]:
del df_copy['growth']

In [151]:
df_copy.columns

Index(['size', 'time', 'price'], dtype='object')

In [157]:
df_copy = df.copy()
df_continent = df_copy[(df_copy['continent']==1 )& (df_copy['brand']==1)]

In [159]:
df_continent.head()

continent  brand  size  period  price
3           1      1   8.0   34.88   69.0
11          1      1  10.4   17.67   54.0
12          1      1   7.4   16.41   39.0
13          1      1   5.4   12.02   29.5
16          1      1   6.0   23.21   42.0

In [161]:
df_size=  df_copy[(df_copy['size']>=10 )& (df_copy['period']>=30)]

In [164]:
df_size['size'].min()

10.0

In [165]:
df_size['period'].min()

31.46

In [166]:
df['brand'].value_counts()

2    24
1    23
3    16
Name: brand, dtype: int64

In [167]:
recode_brand = {'brand':{1:1,2:1,3:2}}

In [168]:
df_recode1 = df.replace(recode_brand)

In [171]:
df_recode1['brand'].value_counts()

1    47
2    16
Name: brand, dtype: int64

In [174]:
def brand(series):
    if series==1:
        return 1
    elif series==2:
        return 1
    elif series==3:
        return 2
df['rebrand'] = df['brand'].apply(brand)
df['rebrand'].value_counts()

1    47
2    16
Name: rebrand, dtype: int64

# numpy pandas 변환

In [181]:
dfnumpy = df.to_numpy()

In [182]:
dfnumpy

array([[  2.  ,   2.  ,  10.7 ,  47.65, 144.  ],
       [  2.  ,   3.  ,  14.  ,  63.13, 215.  ],
       [  2.  ,   2.  ,   9.  ,  58.76, 105.  ],
       [  1.  ,   1.  ,   8.  ,  34.88,  69.  ],
       [  2.  ,   2.  ,  10.  ,  55.53, 134.  ],
       [  2.  ,   2.  ,  10.5 ,  43.14, 129.  ],
       [  2.  ,   2.  ,  16.  ,  54.86, 155.  ],
       [  2.  ,   1.  ,  15.  ,  44.14,  99.  ],
       [  2.  ,   1.  ,   6.5 ,  17.46,  38.5 ],
       [  2.  ,   1.  ,   5.  ,  21.04,  36.5 ],
       [  2.  ,   2.  ,  25.  , 109.38, 260.  ],
       [  1.  ,   1.  ,  10.4 ,  17.67,  54.  ],
       [  1.  ,   1.  ,   7.4 ,  16.41,  39.  ],
       [  1.  ,   1.  ,   5.4 ,  12.02,  29.5 ],
       [  2.  ,   2.  ,  15.4 ,  49.48, 109.  ],
       [  2.  ,   1.  ,  12.4 ,  48.74,  89.5 ],
       [  1.  ,   1.  ,   6.  ,  23.21,  42.  ],
       [  1.  ,   1.  ,   9.  ,  28.64,  65.  ],
       [  1.  ,   3.  ,   9.  ,  44.95, 115.  ],
       [  1.  ,   1.  ,  12.4 ,  23.77,  49.5 ],
       [  1.  ,   1.

In [183]:
dfpandas = pd.DataFrame(dfnumpy)

In [184]:
dfpandas =  pd.DataFrame(data= dfnumpy, columns = df.columns)

In [185]:
dfpandas

continent  brand  size  period  price
0         2.0    2.0  10.7   47.65  144.0
1         2.0    3.0  14.0   63.13  215.0
2         2.0    2.0   9.0   58.76  105.0
3         1.0    1.0   8.0   34.88   69.0
4         2.0    2.0  10.0   55.53  134.0
..        ...    ...   ...     ...    ...
58        1.0    1.0   5.0   16.66   21.5
59        2.0    1.0  21.0   43.00    NaN
60        2.0    2.0   5.0   12.00    NaN
61        2.0    3.0  13.0   20.00    NaN
62        2.0    3.0  31.0   19.00    NaN

[63 rows x 5 columns]